/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmanagementsystem;

import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hasss
 */
public class feerecordview extends javax.swing.JFrame {

    /**
     * Creates new form feerecordview
     */
    public feerecordview() {
        initComponents();
        DBsms db=new DBsms();
        ResultSet rs=db.Displayfeerecord();
        DefaultTableModel tb=(DefaultTableModel)Tablefee.getModel();
        
        try{
        while(rs.next()){
        String []data={rs.getString("Date"),rs.getString("StdId"),rs.getString("StdName"),rs.getString("StdFname"),rs.getString("Class"),rs.getString("Phone"),rs.getString("Address"),rs.getString("Convence"),rs.getString("SchoolFee"),rs.getString("BusFee"),rs.getString("Paid/Unpaid")};
        tb.addRow(data);
        }
        }catch(Exception e){
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablefee = new javax.swing.JTable();
        searchfeee = new javax.swing.JButton();
        searchfee = new javax.swing.JTextField();
        updatefee = new javax.swing.JButton();
        deletefee = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        Tablefee.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Tablefee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "StdId", "StdName", "StdFname", "Class", "Phone", "Address", "Convence", "SchoolFee", "BusFee", "Paid/Unpaid"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tablefee);

        searchfeee.setBackground(new java.awt.Color(255, 255, 255));
        searchfeee.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        searchfeee.setText("Search");
        searchfeee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchfeeeActionPerformed(evt);
            }
        });

        updatefee.setBackground(new java.awt.Color(255, 255, 255));
        updatefee.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        updatefee.setText("Update");
        updatefee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatefeeActionPerformed(evt);
            }
        });

        deletefee.setBackground(new java.awt.Color(255, 255, 255));
        deletefee.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        deletefee.setText("Delete");
        deletefee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletefeeActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(255, 255, 255));
        exit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft Uighur", 1, 48)); // NOI18N
        jLabel1.setText("Fee Submisssion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchfee, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(searchfeee)
                        .addGap(77, 77, 77))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(updatefee)
                                .addGap(18, 18, 18)
                                .addComponent(deletefee))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(495, 495, 495)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchfee, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchfeee)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatefee)
                    .addComponent(deletefee))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchfeeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchfeeeActionPerformed
        // TODO add your handling code here:;
        DBsms db= new DBsms();
        ResultSet rs=db.Searchfee(searchfee.getText());
        DefaultTableModel tb=(DefaultTableModel)Tablefee.getModel();
        tb.setRowCount(0);
        System.out.println("searched");
        try{
            while(rs.next()){
                String []data={rs.getString("Date"),rs.getString("StdId"),rs.getString("StdName"),rs.getString("StdFname"),rs.getString("Class"),rs.getString("Phone"),rs.getString("Address"),rs.getString("Convence"),rs.getString("SchoolFee"),rs.getString("BusFee"),rs.getString("Paid/Unpaid")};
                tb.addRow(data);

            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_searchfeeeActionPerformed

    private void updatefeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatefeeActionPerformed
        // TODO add your handling code here:
        DBsms db=new DBsms();
        DefaultTableModel model=(DefaultTableModel)Tablefee.getModel();
        try{
        for(int i=0; i<model.getRowCount();i++){
            
        String Date=model.getValueAt(i, 0).toString();
        int StdId=Integer.valueOf(model.getValueAt(i, 1).toString());
        String StdName=model.getValueAt(i, 2).toString();
        String StdFname=model.getValueAt(i, 3).toString();
        String Class=model.getValueAt(i, 4).toString();
        int Phone=Integer.valueOf(model.getValueAt(i, 5).toString());
        String Address=model.getValueAt(i, 6).toString();
        String Convence=model.getValueAt(i, 7).toString();
        String SchoolFee=model.getValueAt(i, 8).toString();
        String BusFee=model.getValueAt(i, 9).toString();
        String submission=model.getValueAt(i, 10).toString();
        db.FeeUpdate(Date, StdId, StdName, StdFname, Class, Phone, Address, Convence, SchoolFee, BusFee, submission);
        }
        
            System.out.println("Update");
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_updatefeeActionPerformed

    private void deletefeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletefeeActionPerformed
        // TODO add your handling code here:
        int row=Tablefee.getSelectedRow();
        String tc1=Tablefee.getModel().getValueAt(row, 0).toString();
        String tc2=Tablefee.getModel().getValueAt(row, 1).toString();  
        DBsms db4=new DBsms();
        db4.Deletefee(tc1,tc2);
         ResultSet rs=db4.Displayfeerecord();
        DefaultTableModel tb4=(DefaultTableModel)Tablefee.getModel();
        tb4.setRowCount(0);
        try{
        while(rs.next()){
        String []data={rs.getString("Date"),rs.getString("StdId"),rs.getString("StdName"),rs.getString("StdFname"),rs.getString("Class"),rs.getString("Phone"),rs.getString("Address"),rs.getString("Convence"),rs.getString("SchoolFee"),rs.getString("BusFee"),rs.getString("Paid/Unpaid")};
        tb4.addRow(data);
        }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_deletefeeActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(feerecordview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(feerecordview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(feerecordview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(feerecordview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new feerecordview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tablefee;
    private javax.swing.JButton deletefee;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchfee;
    private javax.swing.JButton searchfeee;
    private javax.swing.JButton updatefee;
    // End of variables declaration//GEN-END:variables
}
